version: "3.8"

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_AUTHENTICATION__1__MECHANISM=password_based
      - EMQX_AUTHENTICATION__1__BACKEND=http
      - EMQX_AUTHENTICATION__1__URL=http://backend:4000/api/mqtt/auth
      - EMQX_AUTHENTICATION__1__METHOD=post
      - EMQX_AUTHENTICATION__1__HEADERS__content-type=application/json
      - EMQX_AUTHENTICATION__1__BODY={"username":"$${username}","password":"$${password}","clientid":"$${clientid}"}
      - EMQX_AUTHENTICATION__1__BODY__clientid=$${clientid}

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=weather_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken1234

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      # - "5432:5432"
       - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: uec_weather_iot
    volumes:
      - uec_weather_iot_pgdata:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

  backend:
    build: .
    container_name: weather-backend
    ports:
      - "4000:4000"
      - "51212:51212"
    depends_on:
      - emqx
      - influxdb
      - postgres
    environment:
      - MQTT_BROKER=mqtt://emqx:1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=mytoken1234
      - INFLUX_ORG=myorg
      - INFLUX_BUCKET=weather_data
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASS=admin1234
      - DB_NAME=uec_weather_iot
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://admin:admin1234@postgres:5432/uec_weather_iot?schema=public
      - JWT_SECRET=UECWeatherSecretKey
      - JWT_REFRESH_SECRET=UECWeatherRefreshSecretKey
      - MQTT_USER=backend
      - MQTT_PASS=backend_secret
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma generate && 
             npx prisma migrate deploy && 
             npx prisma db seed && 
             npm run dev"

volumes:
  influxdb_data:
  grafana_data:
  uec_weather_iot_pgdata: