version: "3.8"

services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      - EMQX_ALLOW_ANONYMOUS=false
      - EMQX_AUTHENTICATION__1__MECHANISM=password_based
      - EMQX_AUTHENTICATION__1__BACKEND=http
      - EMQX_AUTHENTICATION__1__URL=http://backend:4000/api/mqtt/auth
      - EMQX_AUTHENTICATION__1__METHOD=post
      - EMQX_AUTHENTICATION__1__HEADERS__content-type=application/json
      - EMQX_AUTHENTICATION__1__BODY={"username":"$${username}","password":"$${password}","clientid":"$${clientid}"}
      - EMQX_AUTHENTICATION__1__BODY__clientid=$${clientid}

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_TOKEN}

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - uec_weather_iot_pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: weather-backend
    ports:
      - "4000:4000"
      - "51212:51212"
    depends_on:
      - emqx
      - influxdb
      - postgres
    environment:
      - MQTT_BROKER=mqtt://emqx:1883
      - INFLUX_URL=http://influxdb:8086
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - DB_HOST=postgres
      - DB_USER=${POSTGRES_USER}
      - DB_PASS=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_MODEL=${GEMINI_MODEL}
      - GROQ_MODEL=${GROQ_MODEL}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma db push && 
             npm run dev"

volumes:
  influxdb_data:
  uec_weather_iot_pgdata: